export const mockBlocks = [
    {
        index: 0,
        freq: 100,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 0,
        end: 200,
    },
    {
        index: 1,
        freq: 150,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 200,
        end: 400,
    },
    {
        index: 2,
        freq: 200,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 400,
        end: 600,
    },
    {
        index: 3,
        freq: 250,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 600,
        end: 800,
    },
    {
        index: 4,
        freq: 300,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 800,
        end: 1000,
    },
    {
        index: 5,
        freq: 350,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 1000,
        end: 1200,
    },
    {
        index: 6,
        freq: 400,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 1200,
        end: 1400,
    },
    {
        index: 7,
        freq: 450,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 1400,
        end: 1600,
    },
];

export const mockBlocks2 = [
    {
        index: 0,
        freq: 300,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 50,
        end: 400,
    },
    {
        index: 1,
        freq: 288,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 400,
        end: 700,
    },
    {
        index: 2,
        freq: 276,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 700,
        end: 1000,
    },
    {
        index: 3,
        freq: 260,
        gain: 10,
        type: 'center',
        osc: 'triangle',
        beg: 1000,
        end: 1600,
    },
];
